### ISSUE TITLE
P2-Project Setup feedback

### ISSUE THREAD

**Issue by dcmorse** [sunitalanka/liftoff-assignments#1]
Good job on this assignment. I'm marking it mostly complete. 

The way LC scores features, you've got about 2.5 features. We count them like this:

1. MVC java framework with CRUD and relationships
2. login and accounts
3. ?Search?

It'd be good to think of something new, not covered in LC101, that you can do for your feature list. Some web api (datatables.net?)

You can close this issue when you want to.

**Comment by sunitalanka** [comment]
Thank you Dave!! I will try my best to implement a new feature.
