### ISSUE TITLE
P3 Project Planning feedback on wireframes

### ISSUE THREAD

**Issue by dcmorse** [sunitalanka/liftoff-assignments#2]
On your wireframes, I'm only really happy with the design of the student/admin login one, and that's so standard already. 

The other ones don't feel very well thought through to me, for example on (2), how does the user select which student will be edited? Will there be a select menu or something else? 

Wireframes should be high-fidelity enough so that the answers to these questions are obvious. The purpose of wireframes, like with many types of communication in Liftoff, is to drive everyone's assumptions out of their brains and into discussion. 

So sometime if you have the time, revisit these. When you do close this issue and I'll reevaluate. (but mainly work on your project!)

**Comment by sunitalanka** [comment]
I totally agree with you, as I was not very clear with my design at that point of my project. I will try to visit back and consider redoing it whenever possible Dave. Thank you once again!!

**Comment by sunitalanka** [comment]
Thank you Dave!!
