### ISSUE TITLE
P3 Project Planning feedback on stories

### ISSUE THREAD

**Issue by dcmorse** [sunitalanka/liftoff-assignments#3]
I wasn't able to give feedback on your user stories, because the [submitted link to the trello board](https://github.com/sunitalanka/liftoff-assignments/tree/master/P3-Project_Planning) which I found here leads me to this screen:

![trello](https://user-images.githubusercontent.com/10550086/43998213-df1428ce-9db5-11e8-9a10-4aca35c23f5f.png)

I think you need to share your trello board with the public. 

If you fix this and would like me to take another look, kindly close this issue. Thanks!
-Dave

**Comment by sunitalanka** [comment]
I made it public now. https://trello.com/b/cnhmhAZY/collegelogproject and copied my link again. Hope it will help you.

**Comment by dcmorse** [comment]
Yes, I think your stories are well written and the right size. Good work.
