### ISSUE TITLE
C1 resume feedback

### ISSUE THREAD

**Issue by dcmorse** [sunitalanka/liftoff-assignments#4]
Overall, good resume

The recommended format we promote for LaunchCoders is usually:

1. Personal Info 
2. Tech Skills 
3. Tech Experience 
4. Other Experience & Education 
5. Everything else 

I would at least try to crunch things down or rearrange them so your project experience (which can include your liftoff project at this point) can appear on page 1. 

I'd puff up your tech buzzwords a little more. Thymeleaf? Spring? People want to know all those things.  Same with your C experience: If it's more than `#include <stdlib.h>`, throw in 1-2 things you linked against in C. 

I would spell it `MySQL` not `MYSQL`.  I'd say `Git and GitHub` instead of `GITHUB`. 

If you can think of other learning resources you've used recently, maybe consider listing them at the end: MOOCs (like Udemy), CS College Courses (at STLCC, UMSL, etc), Technical Books (Pragmatic Programmer, Eloquent JavaScript, etc).

Overall, good job. As soon as you submit the linkedin portion, I'll mark you complete for this assignment.

**Comment by sunitalanka** [comment]
I used online resources: Udemy, Codecademy and Hackerrank as well Dave. I have sent my LinkedIn url in Launchcode canvas comments section. Thank You!!

**Comment by dcmorse** [comment]
Oh, one other thing. 

Instead of `Knowledge in OOPS concepts`, you want to write `Knowledge in OOP concepts`, I'm pretty sure. At least around my office, OOP means Object Oriented Programming, and OOPS is an exclamation "used to show recognition of a mistake or minor accident, often as part of an apology." Like: "Oops! I misspelled OOP". :laughing:

**Comment by sunitalanka** [comment]
Haha.. definitely a typo!
