### ISSUE TITLE
C1 LinkedIn feedback

### ISSUE THREAD

**Issue by dcmorse** [sunitalanka/liftoff-assignments#5]
Please add the following items to your LinkedIn profile:

- Core Skills (some of which should be technical)
- Work History

Also, these would be nice to have:

  - Summary - A brief description about yourself and your journey.
  - Work history details - Ideally highlighting relevant/transferable skills.
  - Your Volunteer Experience
  - Skills and Endorsements - Ideally applicable skills!
  - Add a professional looking picture. Having a picture helps the interviewer see you as more than just a name, or a resume. It also helps the interviewer recognize you when you come in for an interview, and will help them remember you after the interview! Also a picture is a sign of an active profile.

**Comment by sunitalanka** [comment]
Sure, will soon add these to my LinkedIn profile and I don't have any professional looking picture of me, will take one soon and upload it.

**Comment by sunitalanka** [comment]
Hi Dave, updated my LinkedIn profile and Github profile.. but didn't added any profile pic for my Github.
If I am missing any thing on my profiles then, Please let me know. Thank you!!
